name: Continuous Check

on: [push]

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: ./code/jvm/gradlew -p code/jvm check --info
